Change the strategy of checking for num-bigint or rug backend in ci
Signed-off-by: maurges <nikita@dfns.co>

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -114,15 +114,17 @@ jobs:
         # We can't set --all-features as that will set backend-num-bigint which overrides rug, so we list all features except that
         features=std,hd-wallet,serde,state-machine,all-curves,hd-slip10,hd-stark,spof,insecure-assume-preimage-known,__internal_doctest,backend-rug
 
-        # Check that num-bigint was not present as a dependency of fast-paillier
-        found=$(cargo tree --no-default-features --features $features --no-dedupe |
-          # In the output of cargo tree, find lines between fast-paillier,
-          # which with this indentation means it was a top-level dependency,
-          # until another top-level dependency, and in those lines grep for
-          # num-bigint
-          awk '/^├── fast-paillier/{p=1;next} /^[└├]/{p=0} p' | grep num-bigint -q || echo NOTFOUND)
-        if [ NOTFOUND != "$found" ]; then
+        # Check that num-bigint was not present as a dependency of fast-paillier, but rug was
+        found_rug=$(cargo tree --edges=features --no-default-features --features $features --no-dedupe --invert fast-paillier |
+          grep backend-rug -q || echo NOTFOUND)
+        found_nbi=$(cargo tree --edges=features --no-default-features --features $features --no-dedupe --invert fast-paillier |
+          grep backend-num-bigint -q || echo NOTFOUND)
+        if [ NOTFOUND != "$found_nbi" ]; then
           echo "found num-bigint in dependencies of fast-paillier when the num-bigint backend should not be selected!"
+          exit 1
+        fi
+        if [ NOTFOUND == "$found_rug" ]; then
+          echo "rug not found in dependencies of fast-paillier; this means that our detection script broke"
           exit 1
         fi
 
